language: php

sudo: false

php:
  - 7.0
  - 7.1

env:
  global:
    - coverage=yes
    
before_script:
  - travis_retry composer install --prefer-dist --no-interaction
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  
script: 
    - mkdir -p build/logs
    - if [[ $coverage = 'yes' ]]; then ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
    - if [[ $coverage = 'no' ]]; then ./vendor/bin/phpunit -c phpunit.xml; fi

after_script:
  - if [[ $coverage = 'yes' ]]; then php coveralls.phar -v; fi    

matrix:
  include:
    - php: 7.1
      env: coverage=yes
  allow_failures:
    - env: coverage=yes
  fast_finish: true  
